# W6 inclass activity
## IVan Zepeda
C0883949

In [1]:
import pymongo
from pymongo import MongoClient
client = MongoClient()

In [2]:
# get list of database name
db_lists = client.list_database_names()
print(db_lists)

['admin', 'config', 'local', 'test']


In [3]:
# get list of collection name
coll_lists = client.test.list_collection_names()
print(coll_lists)

['employee', 'test.employee']


# Advanced MongoDB Query

In [13]:
x = client.test.employee.find_one()
print(x)
for i,x in enumerate(client.test.employee.find()):
    print(i,x)

{'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
0 {'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
1 {'_id': 11, 'name': 'John', 'address': 'Highway 37'}
2 {'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
3 {'_id': 13, 'name': 'Amy', 'address': 'Close st 652'}
4 {'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
5 {'_id': 15, 'name': 'Michael', 'address': 'Valley 345'}
6 {'_id': 16, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
7 {'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
8 {'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
9 {'_id': 19, 'name': 'Viola', 'address': 'Sideway Ave'}


In [27]:
myquery = {"$and": [{'address':{'$regex':'^Y'}},
                  {'address':{'$regex':"1"}},
                  {'name':{'$ne':"Nicky"}}
                 ]}
mydoc = client.test.employee.find(myquery)
for x in mydoc:
    print(x)
print(mydoc.count()) #DeprecationWarning: count is deprecated. Use Collection.count_documents instead.

{'_id': 16, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
2


/var/folders/n5/2wsllrvs6h9862hcd58z1ybh0000gn/T/ipykernel_44526/3204370120.py:8: DeprecationWarning: count is deprecated. Use Collection.count_documents instead.
  print(mydoc.count()) #DeprecationWarning: count is deprecated. Use Collection.count_documents instead.


In [28]:
myquery = {'address':{"$gt":"S"}}
mydoc = client.test.employee.find(myquery)
for x in mydoc:
    print(x)

{'_id': 15, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 16, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 19, 'name': 'Viola', 'address': 'Sideway Ave'}


In [29]:
# sort("name",1) #ascending
# sort("name",-1) #descending

mydoc = client.test.employee.find().sort('name')
for x in mydoc:
    print(x)

{'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
{'_id': 13, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 15, 'name': 'Michael', 'address': 'Valley 345'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 16, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 19, 'name': 'Viola', 'address': 'Sideway Ave'}


## Update one record

In [10]:
for x in client.test.employee.find():
    print(x)
    
myquery = {"address": "Valley 345"}
newvalues = {'$set': {"address":"Canyon 123"}}

client.test.employee.update_one(myquery, newvalues)

for x in client.test.employee.find():
    print(x)

    # Segun el profe, si meto el query en en find, aplicaria algo como un WHERE... no le entendi, y no me salio, 

{'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 15, 'name': 'Michael', 'address': 'Canyon 123'}
{'_id': 16, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 19, 'name': 'Viola', 'address': 'Sideway Ave'}
{'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Amy', 'address': 'Close st 652'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 15, 'name': 'Michael', 'address': 'Cany

### Update many records`m

In [13]:
myq={'address':{'$regex':'^C'}}
newvalues={'$set':{'name':'Minnie'}}

x=client.test.employee.update_many(myq, newvalues)
print(x.modified_count, 'documents updated')

for x in client.test.employee.find():
    print(x)


0 documents updated
{'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
{'_id': 11, 'name': 'John', 'address': 'Highway 37'}
{'_id': 12, 'name': 'Peter', 'address': 'Lowstreet 27'}
{'_id': 13, 'name': 'Minnie', 'address': 'Close st 652'}
{'_id': 14, 'name': 'Hannah', 'address': 'Mountain 21'}
{'_id': 15, 'name': 'Minnie', 'address': 'Canyon 123'}
{'_id': 16, 'name': 'Vicky', 'address': 'Yellow Garden 124'}
{'_id': 17, 'name': 'Nicky', 'address': 'Yellow Garden 23'}
{'_id': 18, 'name': 'Nancy', 'address': 'Younge Ave. 123'}
{'_id': 19, 'name': 'Viola', 'address': 'Sideway Ave'}


In [17]:
# rename field "Name" to "LastName"

client.test.employee.update_many({}, {"$rename": {"name": "last_name"}})

for x in client.test.employee.find():
    print(x)


{'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
{'_id': 11, 'address': 'Highway 37', 'last_name': 'John'}
{'_id': 12, 'address': 'Lowstreet 27', 'last_name': 'Peter'}
{'_id': 13, 'address': 'Close st 652', 'last_name': 'Minnie'}
{'_id': 14, 'address': 'Mountain 21', 'last_name': 'Hannah'}
{'_id': 15, 'address': 'Canyon 123', 'last_name': 'Minnie'}
{'_id': 16, 'address': 'Yellow Garden 124', 'last_name': 'Vicky'}
{'_id': 17, 'address': 'Yellow Garden 23', 'last_name': 'Nicky'}
{'_id': 18, 'address': 'Younge Ave. 123', 'last_name': 'Nancy'}
{'_id': 19, 'address': 'Sideway Ave', 'last_name': 'Viola'}


## Delete One Document
by deleting one, but there are many docs, only the first match will be deleted

In [18]:
myquery = {'address':"Mountain 21"}
client.test.employee.delete_one(myquery)


In [19]:

for x in client.test.employee.find():
    print(x)


{'_id': ObjectId('647e6936fef1d7414af8aa78'), 'Name': 'Raj Kumar', 'Address': 'Sears Street , NZ', 'Age': '42'}
{'_id': 11, 'address': 'Highway 37', 'last_name': 'John'}
{'_id': 12, 'address': 'Lowstreet 27', 'last_name': 'Peter'}
{'_id': 13, 'address': 'Close st 652', 'last_name': 'Minnie'}
{'_id': 15, 'address': 'Canyon 123', 'last_name': 'Minnie'}
{'_id': 16, 'address': 'Yellow Garden 124', 'last_name': 'Vicky'}
{'_id': 17, 'address': 'Yellow Garden 23', 'last_name': 'Nicky'}
{'_id': 18, 'address': 'Younge Ave. 123', 'last_name': 'Nancy'}
{'_id': 19, 'address': 'Sideway Ave', 'last_name': 'Viola'}



## Delete Many Documents
you can use a count to get alll documents deleted

In [21]:
myquery={'address':{'$regex':'^Y'}}
x=client.test.employee.delete_many(myquery)
print(x.deleted_count, 'documents deleted')

3 documents deleted


## Delete all documents

In [22]:
x = client.test.employee.delete_many({}) #open dictionary, all will match
print(x.deleted_count, "deleted documents")

6 deleted documents


In [23]:
for x in client.test.employee.find():
    print(x)

## Drop collection

In [24]:
# collection name, dot drop
client.test.employee.drop()

In [26]:
client.test.collection_names()

/var/folders/n5/2wsllrvs6h9862hcd58z1ybh0000gn/T/ipykernel_971/188177445.py:1: DeprecationWarning: collection_names is deprecated. Use list_collection_names instead.
  client.test.collection_names()


['test.employee']

In [27]:
client.test.test.employee.drop()

In [28]:
client.test.collection_names()

/var/folders/n5/2wsllrvs6h9862hcd58z1ybh0000gn/T/ipykernel_971/188177445.py:1: DeprecationWarning: collection_names is deprecated. Use list_collection_names instead.
  client.test.collection_names()


[]



## 
## 

# Vectors

## 

In [29]:
import numpy as np

In [30]:
vector_row= np.array([1,2,3])

In [54]:
vector = np.array([1,2,3,4,5,6,4])

In [36]:
vector[2]

3

In [39]:

print(vector[:3],vector[3:])


[1 2 3] [4 5 6]


  
  
  
 0 base index. the end in slicing, DO NOT include the limit,   
 But START DO include the initial... maybe to the 0 base




In [40]:
# do it but backwards
print('to print 4 I should use the -3 index',vector[-3])

to print 4 I should use the -3 index 4


In [41]:
print(vector[:-3])

[1 2 3]


In [43]:
vector[2::-1]

array([3, 2, 1])

**Obtaining the indexes of numpy array**  
Different methods, but will understand the output,  
while the for will get all matches, a list.index will get only the first match  
but np.where, whill brin all indeces

In [60]:
target=4
for i,n in enumerate(vector):
    if(n == target):
        print("[for] index is",i)
    
print("[list] index is",list(vector).index(target))  


i, = np.where(vector == target) # integers
print('[where] index is',i)
# i, = np.where(np.isclose(a, value)) # floating-point

[for] index is 3
[for] index is 6
[list] index is 3
[where] index is [3 6]



# MATRIX
2D array, or nested list

In [63]:
matrix = np.array([[1,2],[2,3],[7,9]])
matrix

array([[1, 2],
       [2, 3],
       [7, 9]])

In [69]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                  ])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
matrix[1,1]

5

In [71]:
matrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [75]:
matrix[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [76]:
matrix = np.array([[1,2,3,4],
                   [4,5,6,7],
                   [7,8,9,10],
                  ])

In [77]:
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

(3, 4)
12
2


## Dot product

In [78]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [79]:
np.dot(vector_a, vector_b)

32

In [88]:
matrix_a = np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,8]])
matrix_c = np.array([[1,3,1],[1,3,1]])


In [81]:
np.dot(matrix_a,matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [82]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [84]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [85]:
a= [[1,2],[2,3]]
b= [[3,5],[5,9]]
c = np.matmul(a,b)
print(c)

[[13 23]
 [21 37]]


**Number of Columns on Matrix1 should be the same as Number of Rows in Matrix2**  
Shape 0 = rows  
Shape 1 = cols

In [91]:
print(matrix_c.shape)
print(matrix_c.shape[0])
print(matrix_c.shape[1])


(2, 3)
2
3


In [96]:
#funct to receive inpyt of 2 matrix, check if can use matmul. if yes, calculate, l
def is_matmul(m1,m2):
    if(m1.shape[1] == m2.shape[0]):
        print("is matmul able")
        print( np.matmul(m1,m2))
    else:
        print("it is not matmul able")
    
    


In [97]:
matrix_a = np.array([[1,1],[1,1],[1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,8]])
matrix_c = np.array([[2,3,9],[7,3,5],[5,3,2]])
matrix_d = np.array([[1,3,1],[1,3,1]])

In [102]:
print("\n\tmatrix_a,matrix_b")
is_matmul(matrix_a,matrix_b)
print("\n\tmatrix_b,matrix_c")
is_matmul(matrix_b,matrix_c)
print("\n\tmatrix_d,matrix_a")
is_matmul(matrix_d,matrix_a)
print("\n\tmatrix_a,matrix_d")
is_matmul(matrix_a,matrix_d)



	matrix_a,matrix_b
it is not matmul able

	matrix_b,matrix_c
is matmul able
[[28 15 26]
 [28 15 26]
 [63 36 40]]

	matrix_d,matrix_a
is matmul able
[[5 6]
 [5 6]]

	matrix_a,matrix_d
is matmul able
[[2 6 2]
 [2 6 2]
 [3 9 3]]
