# Question 1 (10 marks)

Use a function and use input method to test your code

Given an integer array nums, return the maximum difference between two successive elements in its sorted form. If the array contains less than two elements, return 0.

You must write an algorithm that runs in linear time and uses linear extra space.

Example 1:

Input: nums = [3,6,9,1] Output: 3 Explanation: The sorted form of the array is [1,3,6,9], either (3,6) or (6,9) has the maximum difference 3. 

Example 2:

Input: nums = [10] Output: 0 Explanation: The array contains less than 2 elements, therefore return 0.




In [7]:
#Answer

def max_dif(nums):
    if(type(nums)==str):
        nums=nums.split()
        nums=[int(x) for x in nums]
    if(len(nums)<=2):
        return 0
    nums.sort()
    max_difference=0
    for i in range(len(nums)-1):
        if((nums[i+1]-nums[i])>=max_difference):
            max_difference=(nums[i+1]-nums[i])
    return max_difference
        
    
    
print(max_dif([3,6,9,1]))
print(max_dif([10]))

3
0


In [9]:
print(max_dif(input("give many numbers separated by space only: ")))

give many numbers separated by space only: 3 5 7 88
81


# Question 2 (15 marks)

You are given an n x n 2D matrix representing an image, define a function to rotate the image by n*90 degrees (clockwise).

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly. DO NOT allocate another 2D matrix and do the rotation.

Your code should work for any given value of n.
write a function and use input method to test the code. 

Example 1:

n=1 (90 degree rotation)

Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]

Output: [[7,4,1],[8,5,2],[9,6,3]]





In [41]:
import numpy as np
#Answer
""" """
def rotate_image(n):
    n=int(n)
    matrix=[[1,2,3],[4,5,6],[7,8,9]]
    expected=np.array([[7,4,1],[8,5,2],[9,6,3]])
    mat= np.array(matrix)
    print(f"Original Matrix:")
    print(mat)
    print(f"Rotated Matrix {n} times 90º")
    for i in range(n):
        mat=mat[::-1].T
    print(mat)
    if(n == 1):
        print("Expected Matrix rotated 1 time 90º")
        print(expected)
    
rotate_image(1)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated Matrix 1 times 90º
[[7 4 1]
 [8 5 2]
 [9 6 3]]
Expected Matrix rotated 1 time 90º
[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [39]:
rotate_image(input('write the times to turn the matrix: '))

write the times to turn the matrix: 2
Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rotated Matrix 2 times 90º
[[9 8 7]
 [6 5 4]
 [3 2 1]]


# Question 3 (15 Marks)

Given a rows x cols binary matrix filled with 0's and 1's, write a function and use input method to find the largest rectangle containing only 1's and return its area.

Input: matrix = [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]]

Output: 6


Example 2:

Input: matrix = [["0"]]

Output: 0

you can print the example matrix above to get better visual understanding of the quesion

In [54]:
#Answer

"""
This question can be solved in a recursive method, a function that is called within a whille loop. 
the the loop will scann all the elements of the matrix, conevrting each node into a different value, 
then comparing to 0 or 1, the loop will continue in that direction or not.
It is similar to a problem called Number of Islands in Leetcode.
But Islands Can have any form.
In this case is REctangle, then, will only consider the same amount of length and height. 
Also, can loop in a certain order, left-to-right, and up to down
"""

"""A second approach is to do sub-matrix, and just analize if it contains 1s on them"""

""" A third approach is to do 2 nested loops, cancelling the loop once it has found a 0.
This is the approach I will take"""
"""
[['1' '0' '1' '0' '0']
 ['1' '0' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '0' '0' '1' '0']]"""

import numpy as np

def largest_rect(matrix):
    mat= np.array(matrix)
    print(mat)
    largest=0
    rows=len(matrix)
    cols=len(matrix[0])
    print(rows)#rows
    print(cols)#cols

    count=0
    count_row=0
    count_col=0
    max_count_row=1
    max_count_col=1
    step=0
    for row in range(len(matrix)):
        count_row=0
        count_col=0
        step=0
        for col in range(len(matrix)-1):
#             if(step>0):
#                 count_row+=1
            if(matrix[row][col+step]=="1"): 
                count_col+=1
                max_count_row+=1
                max_count_col+=1
            if(matrix[row][col]=="0"): 
                if(max_count_row>=count_col): # and count_col!=0
                    max_count_row=count_col
                    
                if(max_count_row>=count_col): # and count_col!=0
                    max_count_row=count_col
                if(col<cols):
                    step+=1
                else:
                    continue
    print(f"row: {max_count_row}  * cols: {max_count_col}")   
    return max_count_row*max_count_col
                
    
largest_rect([["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]])

[['1' '0' '1' '0' '0']
 ['1' '0' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '0' '0' '1' '0']]
4
5
row: 2  * cols: 9


18

# Good Luck 